name 'jrussell-logstash'
version '1.0.0'

author 'Josh Russell'
license 'Apache License, Version 2.0'
project_page 'https://github.com/j-russell/puppet-logstash'
source 'https://github.com/j-russell/puppet-logstash'
summary 'Install and configure Logstash'
description 'Install and configure Logstash'
dependency 'puppetlabs/stdlib', '>=2.2.1'
dependency 'ripienaar/concat', '>=0.1.0'
